In [34]:
pwd

'/Users/hongshanguo/Library/CloudStorage/OneDrive-TheUniversityOfHongKong/Misc/thermalcomfortdb'

In [2]:
import pandas as pd
from glob import glob

In [3]:
f=glob('dbs/ashrae/*.csv')

In [16]:
dat={}
for k in f:
    name=k.replace('dbs/','').replace('.csv','').replace('ashrae_','').replace('ASHRAE_','')
    dat[name]=pd.read_csv(k,encoding='unicode_escape').dropna(axis=1, how='all')

/var/folders/wj/z9j921hd3ysfbgj2tx3b554m0000gn/T/ipykernel_46647/2630473060.py:4: DtypeWarning: Columns (8,11,14,16,17,32,48,58) have mixed types. Specify dtype option on import or set low_memory=False.
  dat[name]=pd.read_csv(k,encoding='unicode_escape').dropna(axis=1, how='all')
/var/folders/wj/z9j921hd3ysfbgj2tx3b554m0000gn/T/ipykernel_46647/2630473060.py:4: DtypeWarning: Columns (10,11,13,18,19,34,50) have mixed types. Specify dtype option on import or set low_memory=False.
  dat[name]=pd.read_csv(k,encoding='unicode_escape').dropna(axis=1, how='all')
/var/folders/wj/z9j921hd3ysfbgj2tx3b554m0000gn/T/ipykernel_46647/2630473060.py:4: DtypeWarning: Columns (5,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  dat[name]=pd.read_csv(k,encoding='unicode_escape').dropna(axis=1, how='all')

In [17]:
dat.keys()

dict_keys(['2018_db2.0', '2018_db2.01', '2022_db_measurements_v2.1.0', '2022_db_metadata'])

In [19]:
dat['2018_db2.0'].columns#.dropna(axis=1, how='all')

Index(['Publication (Citation)', 'Data contributor', 'Year', 'Season',
       'Köppen climate classification', 'Climate', 'City', 'Country',
       'Building type', 'Cooling startegy', 'Age', 'Sex', 'Thermal sensation',
       'Thermal sensation acceptability ', 'Thermal preference',
       'Air movement acceptability', 'Air movement preference',
       'Thermal comfort', 'PMV', 'PPD', 'SET', 'Clo', 'Met', 'activity_10',
       'activity_20', 'activity_30', 'activity_60', 'Air temperature (°C)',
       'Air temperature (°F)', 'Ta_h (°C)', 'Ta_h (°F)', 'Ta_m (°C)',
       'Ta_m (°F)', 'Ta_l (°C)', 'Ta_l (°F)', 'Operative temperature (°C)',
       'Operative temperature (°F)', 'Radiant temperature (°C)',
       'Radiant temperature (°F)', 'Globe temperature (°C)',
       'Globe temperature (°F)', 'Tg_h (°C)', 'Tg_h (°F)', 'Tg_m (°C)',
       'Tg_m (°F)', 'Tg_l (°C)', 'Tg_l (°F)', 'Relative humidity (%)',
       'Humidity preference', 'Humidity sensation', 'Air velocity (m/s)',
       'Air velocity (fpm)', 'Velocity_h (m/s)', 'Velocity_h (fpm)',
       'Velocity_m (m/s)', 'Velocity_m (fpm)', 'Velocity_l (m/s)',
       'Velocity_l (fpm)', 'Subject´s height (cm)', 'Subject´s weight (kg)',
       'Blind (curtain) ', 'Fan', 'Window', 'Door', 'Heater',
       'Outdoor monthly air temperature (°C)',
       'Outdoor monthly air temperature (°F)', 'Database'],
      dtype='object')

In [33]:
dat['2018_db2.0']#[['PMV','PPD','SET','Thermal sensation']].dropna()

,Publication (Citation),Data contributor,Year,Season,Köppen climate classification,Climate,City,Country,Building type,Cooling startegy,...,Subject´s height (cm),Subject´s weight (kg),Blind (curtain),Fan,Window,Door,Heater,Outdoor monthly air temperature (°C),Outdoor monthly air temperature (°F),Database
0,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,162.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
1,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,154.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
2,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,173.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
3,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,167.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
4,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,178.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107457,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107458,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107459,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107460,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107461,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [31]:
dat['2018_db2.0'][['PMV','PPD','SET','Thermal sensation']].dropna()

#TSV - Thermal Sensation Vote [-3 , 3] Actual
#PMV - Predicted Mean Vote [-3,3] Pred <-

        PMV   PPD    SET  Thermal sensation
74     -1.1  32.0  22.20               -1.3
75     -0.1   5.0  24.45               -1.4
76     -0.4   8.0  23.74                0.6
77     -0.3   7.0  24.49                0.5
78     -0.4   9.0  23.90                1.6
...     ...   ...    ...                ...
103913  0.0   5.0  24.75                2.0
103914 -0.1   5.0  24.31                2.5
103915 -0.4   8.0  22.99                0.0
103916 -0.3   7.0  23.44                1.0
103917 -0.3   7.0  23.69                0.1

[66397 rows x 4 columns]

An additional 25,288 rows of data from the original ASHRAE RP-884 database are included. The most recent update (version 2.1) has 6,441 new rows of data, bringing the total number of entries to 109,033. <- This is per dryad https://datadryad.org/stash/dataset/doi:10.6078/D1F671 or Parkinson, Thomas et al. (2022). ASHRAE global database of thermal comfort field measurements [Dataset]. Dryad. https://doi.org/10.6078/D1F671
 
Data update until 2022, showing signs and indications of this going a bit forward rather than backward on what is available, etc. 

Connections to [Annex69](https://www.iea-ebc.org/Data/Sites/1/media/docs/FBF/fbf_2017_presentations/iea-fbf-october-2017-presentation-yao-meng-iea-ebc-annex-69.pdf).

In [22]:
dat['2022_db_metadata']['met_source'].value_counts()

met_source
original_data    397
rp884            205
ghcn_d            49
Name: count, dtype: int64

In [23]:
dat['2022_db_measurements_v2.1.0'].columns

Index(['index', 'record_id', 'building_id', 'timestamp', 'season',
       'subject_id', 'age', 'gender', 'ht', 'wt', 'ta', 'ta_h', 'ta_m', 'ta_l',
       'top', 'tr', 'tg', 'tg_h', 'tg_m', 'tg_l', 'rh', 'vel', 'vel_h',
       'vel_m', 'vel_l', 'met', 'clo', 'activity_10', 'activity_20',
       'activity_30', 'activity_60', 'thermal_sensation',
       'thermal_acceptability', 'thermal_preference', 'thermal_comfort',
       'air_movement_acceptability', 'air_movement_preference',
       'blind_curtain', 'fan', 'window', 'door', 'heater', 't_out', 'rh_out',
       't_out_isd', 'rh_out_isd', 'set', 'pmv', 'ppd', 'pmv_ce', 'ppd_ce',
       't_mot_isd'],
      dtype='object')

In [25]:
dat['2018_db2.0']

,Publication (Citation),Data contributor,Year,Season,Köppen climate classification,Climate,City,Country,Building type,Cooling startegy,...,Subject´s height (cm),Subject´s weight (kg),Blind (curtain),Fan,Window,Door,Heater,Outdoor monthly air temperature (°C),Outdoor monthly air temperature (°F),Database
0,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,162.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
1,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,154.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
2,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,173.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
3,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,167.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
4,"Kwok, Alison G., and Chungyoon Chun. ""Thermal ...",Kwok Alison,2000.0,Summer,Cfa,Humid subtropical,Tokyo,Japan,Classroom,Air Conditioned,...,178.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,77.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107457,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107458,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107459,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107460,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
107461,"Kwok, A.G. ""Thermal Comfort in Tropical Classr...",Alison Kwok,1996.0,Winter,As,Tropical dry savanna,Honolulu,United States,Classroom,Air Conditioned,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [27]:
X1Y=dat['2018_db2.0']

#### ASHRAE-Global Dataset ONE (2018/2022)


#### Chinese TC Dataset TWO 2023 


#### W/ Physiological Dataset THREE (2024 TBC)



EDA Thermal comfort

X1X2Y

X2 -> Physiological Information (8/EU, US, CN) [X1**X2**Y]

Y

Robin Robin Test